services:
  - type: web
    name: projek-umkm-laravel
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        fromDatabase: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: $DATABASE_HOST
      - key: DB_PORT
        value: $DATABASE_PORT
      - key: DB_DATABASE
        value: $DATABASE_NAME
      - key: DB_USERNAME
        value: $DATABASE_USERNAME
      - key: DB_PASSWORD
        value: $DATABASE_PASSWORD
